### ISSUE TITLE
Register Account | No error handeling when the password field does not match the confirm password field

### ISSUE THREAD

**Issue by alexwholland** [bhavanvir/SENG-350#15]
## Overview
When registering an account, if the user incorrectly confirms their password an error should be displayed indicating that the passwords do not match. Notice in the attached image, errors are displayed for incorrectly fields in the username and email boxes but not when mismatched passwords are inputted.

<img width="585" alt="noMatch" src="https://user-images.githubusercontent.com/64433812/198862069-e56ca135-521a-4927-ac31-970332061e90.png">

## Notes
This issue was mentioned with a todo in PR #14

**Comment by bhavanvir** [comment]
Refer to PR #16 where this issue was resolved
