### ISSUE TITLE
Favicon icon should be update to our logo

### ISSUE THREAD

**Issue by alexwholland** [bhavanvir/SENG-350#35]
Currently the favicon is:
![Screen Shot 2022-11-21 at 4 55 23 PM](https://user-images.githubusercontent.com/64433812/203188274-6b7c355f-ab5b-4e7e-b95a-a0fc30cdbcdf.png)

Should be:
![Screen Shot 2022-11-21 at 4 56 31 PM](https://user-images.githubusercontent.com/64433812/203188418-285b7241-e5ad-41e8-9b8d-d261bf09ac4d.png)

**Comment by bhavanvir** [comment]
See #38.
